name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

routes = [
  { pattern = "vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "ava.game.naver.com.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "df.game.naver.com.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "cache.netflix.com.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "bakrie.ac.id.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "quiz.vidio.com.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "investor.fb.com.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "img.email2.vidio.com.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "app.gopay.co.id.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "graph.instagram.com.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "support.zoom.us.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "www.uii.ac.id.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "untar.ac.id.vpn.stupidworld.web.id", custom_domain = true },
  { pattern = "world.stupx2.my.id", custom_domain = true },
  { pattern = "ava.game.naver.com.world.stupx2.my.id", custom_domain = true },
  { pattern = "df.game.naver.com.world.stupx2.my.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.world.stupx2.my.id", custom_domain = true },
  { pattern = "cache.netflix.com.world.stupx2.my.id", custom_domain = true },
  { pattern = "bakrie.ac.id.world.stupx2.my.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.world.stupx2.my.id", custom_domain = true },
  { pattern = "quiz.vidio.com.world.stupx2.my.id", custom_domain = true },
  { pattern = "investor.fb.com.world.stupx2.my.id", custom_domain = true },
  { pattern = "img.email2.vidio.com.world.stupx2.my.id", custom_domain = true },
  { pattern = "app.gopay.co.id.world.stupx2.my.id", custom_domain = true },
  { pattern = "graph.instagram.com.world.stupx2.my.id", custom_domain = true },
  { pattern = "support.zoom.us.world.stupx2.my.id", custom_domain = true },
  { pattern = "www.uii.ac.id.world.stupx2.my.id", custom_domain = true },
  { pattern = "untar.ac.id.world.stupx2.my.id", custom_domain = true },
]

[[kv_namespaces]]
binding = "SIREN"
id = "f91b394c2f614fe597dfc58622ae9a96"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "f282b878-8711-45a1-8c69-5564172123c1"


MAIN_PAGE_URL = "https://raw.githubusercontent.com/stpdwrld/siren/refs/heads/master/web/index.html"
SUB_PAGE_URL  = "https://raw.githubusercontent.com/stpdwrld/siren/refs/heads/master/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/stpdwrld/siren/refs/heads/master/web/link.html"
CONVERTER_PAGE_URL = "https://raw.githubusercontent.com/stpdwrld/siren/refs/heads/master/web/converter.html"
